apiVersion: apps/v1
kind: Deployment
metadata:
  name: izota-dummy-deployment-frontend2
  namespace: dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izota-dummy-frontend2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: izota-dummy-frontend2
    spec:
      restartPolicy: Always
      containers:
        - name: izota-dummy-frontend2
          image: DOCKER_IMAGE_FRONTEND
          imagePullPolicy: Always
          env:
          - name: AppSettings__ExternalAPIMessageA
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: AppSettings__ExternalAPIMessageA
          - name: AppSettings__ExternalAPIMessageB
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: AppSettings__ExternalAPIMessageB
          - name: AppSettings__ExternalAPIMessageC
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: AppSettings__ExternalAPIMessageC
          - name: AppSettings__StartupTime
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: AppSettings__StartupTime
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: izota-dummy-frontend2-service
  namespace: dev-frontend
spec:
  selector:
    app: izota-dummy-frontend2
  ports:
    - port: 80
      targetPort: 8080