apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: dev-frontend
type: Opaque
data:
  mongodbUri: bW9uZ29kYjovL2l6b3RhOjEyM3F3ZUAxMjMuMzEuMjkuMjExOjI3MDE1Cg==
  dbConnection: SG9zdD0xMjMuMzEuMjkuMjExO1BvcnQ9NTQzMjtEYXRhYmFzZT1pem90YS10ZXN0O1VzZXJuYW1l
  PWl6b3RhO1Bhc3N3b3JkPTEyM3F3ZQo=
  MQHost: MTIzLjMxLjI5LjIxMQ==
  MQUserName: aXpvdGEK
  MQPassword: MTIzcXdlCg==
