apiVersion: apps/v1
kind: Deployment
metadata:
  name: izota-dummy-deployment
  namespace: sanbox-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izota-dummy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: izota-dummy
    spec:
      restartPolicy: Always
      containers:
        - name: izota-dummy
          image: DOCKER_IMAGE_FRONTEND
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          env:
          - name: ExternalAPIMessageA
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: ExternalAPIMessageA
          - name: ExternalAPIMessageB
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: ExternalAPIMessageB
          - name: ExternalAPIMessageC
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: ExternalAPIMessageC
          - name: StartupTime
            valueFrom:
              configMapKeyRef:
                name: izota-dummy-config
                key: StartupTime
          - name: MongoConnectionString
            valueFrom:
              secretKeyRef:
                name: db-secret           # Tên của Secret
                key: MONGODB_URI # Tên khóa trong Secret
          - name: PostgresConnectionString
            valueFrom:
              secretKeyRef:
                name: db-secret           # Tên của Secret
                key: PG_DB_CONNECTION # Tên khóa trong Secret
          - name: MQHost
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MQ_HOST
          - name: MQUserName
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MQ_USERNAME
          - name: MQPassword
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MQ_PASSWORD
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: izota-dummy-service
  namespace: sanbox-frontend
spec:
  selector:
    app: izota-dummy
  ports:
    - port: 80
      targetPort: 8080
