apiVersion: apps/v1
kind: Deployment
metadata:
  name: izota-dummy-deployment
  namespace: prod-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izota-dummy-backend
  template:
    metadata:
      labels:
        app: izota-dummy-backend
    spec:
      containers:
        - name: izota-dummy-backend
          image: DOCKER_IMAGE_BACKEND
          imagePullPolicy: Always
          env:
            - name: ExternalAPIMessageA
              valueFrom:
                configMapKeyRef:
                  name: izota-dummy-config
                  key: ExternalAPIMessageA
            - name: ExternalAPIMessageB
              valueFrom:
                configMapKeyRef:
                  name: izota-dummy-config
                  key: ExternalAPIMessageB
            - name: ExternalAPIMessageC
              valueFrom:
                configMapKeyRef:
                  name: izota-dummy-config
                  key: ExternalAPIMessageC
            - name: StartupTime
              valueFrom:
                configMapKeyRef:
                  name: izota-dummy-config
                  key: StartupTime
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: izota-dummy-service
  namespace: prod-backend
spec:
  selector:
    app: izota-dummy-backend
  ports:
    - port: 80
      targetPort: 8080