apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izota-dummy-ingress
  namespace: dev-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dev-frontend-izota.mpire.asia
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: izota-dummy-service
                port:
                  number: 80
