name: Create Docker Secret

on:
  workflow_dispatch:

jobs:
  create-docker-secret-dev:
    runs-on: eos
    steps:
    - name: Create or Update Docker Secret
      env:
        DOCKER_SERVER: ${{ secrets.DOCKER_SERVER }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
      run: |
        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=dev-frontend

        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=dev-backend

  create-docker-secret-sanbox:
    runs-on: eos
    environment: sanbox
    steps:
    - name: Create or Update Docker Secret
      env:
        DOCKER_SERVER: ${{ secrets.DOCKER_SERVER }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
      run: |
        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=sanbox-frontend

        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=sanbox-backend

  create-docker-secret-production:
    runs-on: eos
    environment: production
    steps:
    - name: Create or Update Docker Secret
      env:
        DOCKER_SERVER: ${{ secrets.DOCKER_SERVER }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
      run: |
        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=prod-frontend

        kubectl apply secret docker-registry docker-secret \
          --docker-server=$DOCKER_SERVER \
          --docker-username=$DOCKER_USERNAME \
          --docker-password=$DOCKER_PASSWORD \
          --docker-email=$DOCKER_EMAIL \
          --namespace=prod-backend
