name: Create, update DB Secret

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: eos

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PG_DB_CONNECTION: ${{ secrets.PG_DB_CONNECTION }}
          MQ_HOST: ${{secrets.MQ_HOST }}
          MQ_USERNAME: ${{secrets.MQ_USERNAME }}
          MQ_PASSWORD: ${{ secrets.MQ_PASSWORD }}
        run: |
          echo "Substituting environment variables in the template"
#          envsubst < k8s_secret/dev/db_secret_template.yaml > secret.yaml

      - name: Apply DB Secret
        run: |
          cat secret.yaml
          kubectl apply -f k8s_secret/dev/db_secret_template.yaml
