name: Create, update DB Secret

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          MONGODB_URI: $(echo -n ${{ secrets.MONGODB_URI }} | base64)
          PG_DB_CONNECTION: $(echo -n ${{ secrets.PG_DB_CONNECTION }} | base64)
          MQ_HOST: $(echo -n ${{ secrets.MQ_HOST }} | base64)
          MQ_USERNAME: $(echo -n ${{ secrets.MQ_USERNAME }} | base64)
          MQ_PASSWORD: $(echo -n ${{ secrets.MQ_PASSWORD }} | base64)
        run: |
          echo "Substituting environment variables in the template"
          envsubst < k8s_secret/dev/db_secret_template.yaml > secret.yaml

      - name: Deploy Ingress
          run: |
            kubectl apply -f secret.yaml
