name: Create Docker Secret

on:
  workflow_dispatch:

jobs:
  create-secret:
    runs-on: eos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker Secret
        env:
          DOCKER_SERVER: ${{ secrets.DOCKER_SERVER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
        run: |
          kubectl create secret docker-registry docker-secret \
            --docker-server=$DOCKER_SERVER \
            --docker-username=$DOCKER_USERNAME \
            --docker-password=$DOCKER_PASSWORD \
            --docker-email=$DOCKER_EMAIL \
            --namespace=dev-frontend

          kubectl create secret docker-registry docker-secret \
            --docker-server=$DOCKER_SERVER \
            --docker-username=$DOCKER_USERNAME \
            --docker-password=$DOCKER_PASSWORD \
            --docker-email=$DOCKER_EMAIL \
            --namespace=dev-backend
