name: dummy-release

on:
  repository_dispatch:
    types: [dummy_service_release]
env:
  TAG_PREFIX: 'v'
  PATH_SANBOX_ENV: 'dummy_service/sanbox'
  PATH_PRODUCTION_ENV: 'dummy_service/production'

jobs:
  DeployToSanbox:
    if: |
      github.event.client_payload.ref_name == 'release' &&
      github.event.client_payload.environment == 'sanbox'
    runs-on: eos
    environment: sanbox
    steps:
      - name: Dummy
        run: |
          echo "DOCKER_IMAGE_TAG=${{ github.event.client_payload.docker_image_tag }}"

      - name: Replace docker image in file deployment
        run: |
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}-sanbox|g' ${{ env.PATH_SANBOX_ENV }}/deployments/frontend/deployment.yaml
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}-sanbox|g' ${{ env.PATH_SANBOX_ENV }}/deployments/frontend/deployment-frontend-2.yaml
          sed -i 's|DOCKER_IMAGE_BACKEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}-sanbox|g' ${{ env.PATH_SANBOX_ENV }}/deployments/backend/deployment.yaml
      - name: Deploy Frontend
        run: |
          cat ${{ env.PATH_SANBOX_ENV }}/deployments/frontend/deployment.yaml
      - name: Deploy Frontend 2
        run: |
          cat ${{ env.PATH_SANBOX_ENV }}/deployments/frontend/deployment-frontend-2.yaml
      - name: Deploy Backend
        run: |
          cat ${{ env.PATH_SANBOX_ENV }}/deployments/backend/deployment.yaml

  DeployToProduction:
    if: |
      github.event.client_payload.ref_name == 'release' &&
      github.event.client_payload.environment == 'production'
    runs-on: eos
    environment: production
    steps:
      - name: Dummy
        run: |
          echo "DOCKER_IMAGE_TAG=${{ github.event.client_payload.docker_image_tag }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace docker image in file deployment
        run: |
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}|g' ${{ env.PATH_PRODUCTION_ENV }}/deployments/frontend/deployment.yaml
          sed -i 's|DOCKER_IMAGE_FRONTEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}|g' ${{ env.PATH_PRODUCTION_ENV }}/deployments/frontend/deployment-frontend-2.yaml
          sed -i 's|DOCKER_IMAGE_BACKEND|${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ github.event.client_payload.docker_image_tag }}|g' ${{ env.PATH_PRODUCTION_ENV }}/deployments/backend/deployment.yaml
      - name: Deploy Frontend
        run: |
          cat ${{ env.PATH_DEPLOYMENT_PRODUCTION }}/deployments/frontend/deployment.yaml
      - name: Deploy Frontend 2
        run: |
          cat ${{ env.PATH_DEPLOYMENT_PRODUCTION }}/deployments/frontend/deployment-frontend-2.yaml
      - name: Deploy Backend
        run: |
          cat ${{ env.PATH_DEPLOYMENT_PRODUCTION }}/deployments/backend/deployment.yaml