name: Test

on:
  workflow_dispatch:

jobs:
  test-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Append data to log file
        run: echo "$(date) - Cập nhật log" >> log.txt

      - name: Configure Git
        run: |
          git config --global user.email "<>"
          git config --global user.name "CI Build"

      - name: Commit and Push Changes
        run: |
          git add log.txt
          git commit -m "Cập nhật log tự động từ GitHub Action"
          git push
